[client]
toolbarMode = "minimal"

[logger]
level = "warning"

[theme]
primaryColor="#4294ff"
backgroundColor="#ef9063"
secondaryBackgroundColor="#fa8552"
textColor="#f7f8fa"
font="sans serif"

[browser]
gatherUsageStats = false
