[client]
toolbarMode = "minimal"

[logger]
level = "warning"

[theme]
primaryColor="#4294ff"
backgroundColor="#ef9063"
secondaryBackgroundColor="#356dde"
textColor="#f7f8fa"
font="verdana"

[browser]
gatherUsageStats = false
